<h1>Импорт библиотек

In [3]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [ ]:
def sum_prod(X, V):
    matrix = np.array(X)
    vector = np.array(V)
    result = matrix.dot(vector)

    return f'Результат перемножения: {result[0]},{result[1]}'


print(sum_prod([[4, 1], [2, 2]], [1, 2])) # Результат перемножения: 6,6
print(sum_prod([[2, 5], [1, 6]], [1, 2])) # Результат перемножения: 12,13

<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [ ]:
def binarize(M, threshold=0.5):
    matrix = np.array(M)
    binarize = np.where(matrix > threshold, 1, 0)
    
    return binarize


print(binarize([[0.7, 1.4, 0.5], [0.2, 0.0, 0.3], [3.8, 0.8, 1.3]])) 
#[[1 1 0]
#[0 0 0]
#[1 1 1]]

<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:

def unique_rows(mat):
    unique_elements = []
    for row in mat:
        unique_elements.append(np.unique(row))
    return unique_elements
def unique_columns(mat):
    unique_elements = []
    for col in mat.T:
        unique_elements.append(np.unique(col))
    return unique_elements
print(unique_rows([[1, 1, 3], [5, 5, 6], [7, 8, 9]])) #[array([1, 3]), array([5, 6]), array([7, 8, 9])]
print(unique_columns([[1, 4, 3], [1, 5, 3], [3, 8, 9]]))



<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
def analyze_matrix(m, n):
    mat = np.random.normal(size=(m, n))
    
    # Математическое ожидание и дисперсия
    mean_cols = np.mean(mat, axis=0)
    var_cols = np.var(mat, axis=0)
    
    # Математическое ожидание и дисперсия
    mean_rows = np.mean(mat, axis=1)
    var_rows = np.var(mat, axis=1)
    
    # Гистограммы для каждой строки и столбца
    for i in range(m):
        plt.figure()
        plt.hist(mat[i, :], bins=20)
        plt.title(f'Row {i+1} Histogram')
        plt.show()
    
    for j in range(n):
        plt.figure()
        plt.hist(mat[:, j], bins=20)
        plt.title(f'Column {j+1} Histogram')
        plt.show()
    
    return mean_cols, var_cols, mean_rows, var_rows

mean_cols, var_cols, mean_rows, var_rows = analyze_matrix(3, 4)
print(mean_cols) #[-0.32210668 -0.12306989  0.1434362   0.37129778]
print(var_cols) #[0.68836471 0.43751733 0.79434555 0.07455903]
print(mean_rows) #[ 0.39038247 -0.14836409 -0.18985032]
print(var_rows) #[0.60985877 0.39328    0.49049885]



<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
def chess(m, n, a, b):
    mat = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            if (i + j) % 2 == 0:
                mat[i, j] = a
            else:
                mat[i, j] = b
    return mat

print(chess(3, 3, 1, 0)) 
#[[1. 0. 1.]
#[0. 1. 0.]
#[1. 0. 1.]]

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [ ]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    image = np.full((m, n, 3), background_color, dtype=np.uint8)
    image[1:a+1, 1:b+1] = rectangle_color
    plt.imshow(image)
    plt.show()

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    image = np.full((m, n, 3), background_color, dtype=np.uint8)
    for i in range(m):
        for j in range(n):
            if ((i - m/2)**2 / (a**2) + (j - n/2)**2 / (b**2)) <= 1:
                image[i, j] = ellipse_color
    plt.imshow(image)
    plt.show()

# Тесты
print(draw_rectangle(5, 5, 10, 10, (255, 0, 0), (0, 0, 255)))
print(draw_ellipse(5, 5, 10, 10, (0, 255, 0), (0, 0, 255)))

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
def analyze_time_series(series, p):
    mean = np.mean(series)
    var = np.var(series)
    std = np.std(series)
    
    local_max = []
    local_min = []
    for i in range(1, len(series) - 1):
        if series[i] > series[i-1] and series[i] > series[i+1]:
            local_max.append(i)
        elif series[i] < series[i-1] and series[i] < series[i+1]:
            local_min.append(i)
    
    moving_avg = np.convolve(series, np.ones(p)/p, mode='valid')
    
    return mean, var, std, local_max, local_min, moving_avg

series = np.array([1, 3, 2, 5, 4, 7, 6, 9, 8])
mean, var, std, local_max, local_min, moving_avg = analyze_time_series(series, 3)
print(mean) #5.0
print(var) #6.666666666666667
print(std) #2.581988897471611
print(local_max) #[1, 3, 5, 7]
print(local_min) #[2, 4, 6]
print(moving_avg) #[2.         3.33333333 3.66666667 5.33333333 5.66666667 7.33333333 7.66666667]

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
def one_hot_encoding(labels):
    n_classes = np.max(labels) + 1
    one_hot = np.zeros((len(labels), n_classes))
    one_hot[np.arange(len(labels)), labels] = 1
    return one_hot

labels = np.array([0, 2, 3, 0])
print(one_hot_encoding(labels)) 
#[[1. 0. 0. 0.]
#[0. 0. 1. 0.]
#[0. 0. 0. 1.]
#[1. 0. 0. 0.]]